"""test migration nine

Revision ID: 000483f96d73
Revises: 1e9fa952d520
Create Date: 2025-07-07 15:45:13.420592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000483f96d73'
down_revision: Union[str, Sequence[str], None] = '1e9fa952d520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_nine', sa.String(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_eight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_eight', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_nine')
    # ### end Alembic commands ###
