"""test migration six

Revision ID: 1c867c50ead4
Revises: 7f90c7ad2b36
Create Date: 2025-07-07 15:42:37.110344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c867c50ead4'
down_revision: Union[str, Sequence[str], None] = '7f90c7ad2b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('new_column_test_fix', sa.String(), nullable=True))
    op.drop_column('restaurant', 'new_column_test_five')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('new_column_test_five', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurant', 'new_column_test_fix')
    # ### end Alembic commands ###
