"""test migration eight

Revision ID: 1e9fa952d520
Revises: 9d9b26931f8d
Create Date: 2025-07-07 15:44:13.454633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9fa952d520'
down_revision: Union[str, Sequence[str], None] = '9d9b26931f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('new_column_test_eight', sa.String(), nullable=True))
    op.drop_column('restaurant', 'new_column_test_seven')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('new_column_test_seven', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurant', 'new_column_test_eight')
    # ### end Alembic commands ###
