"""admin restaurant address relationships

Revision ID: 705a00882347
Revises: 8d35db5835e9
Create Date: 2025-07-07 19:07:54.698071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705a00882347'
down_revision: Union[str, Sequence[str], None] = '8d35db5835e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('restaurant_addresses')
    op.add_column('admins', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'admins', ['address_id'])
    op.create_foreign_key(None, 'admins', 'addresses', ['address_id'], ['id'])
    op.add_column('restaurants', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'restaurants', ['address_id'])
    op.create_foreign_key(None, 'restaurants', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_constraint(None, 'restaurants', type_='unique')
    op.drop_column('restaurants', 'address_id')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'address_id')
    op.create_table('restaurant_addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('addresses')
    # ### end Alembic commands ###
