"""test migration five

Revision ID: 7f90c7ad2b36
Revises: bbc8bee13df6
Create Date: 2025-07-07 15:38:41.342874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f90c7ad2b36'
down_revision: Union[str, Sequence[str], None] = 'bbc8bee13df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_five', sa.String(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_four')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_four', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_five')
    # ### end Alembic commands ###
