"""removed test column

Revision ID: 8d35db5835e9
Revises: bdcbf9a755f3
Create Date: 2025-07-07 18:45:43.919707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d35db5835e9'
down_revision: Union[str, Sequence[str], None] = 'bdcbf9a755f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'new_column_test_ten')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_ten', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
