"""test migration seven

Revision ID: 9d9b26931f8d
Revises: 1c867c50ead4
Create Date: 2025-07-07 15:43:30.453227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9b26931f8d'
down_revision: Union[str, Sequence[str], None] = '1c867c50ead4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_seven', sa.String(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_fix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_fix', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_seven')
    # ### end Alembic commands ###
