"""state columns unique

Revision ID: b9abebb0aea2
Revises: d77dddcce6c6
Create Date: 2025-08-28 16:37:21.810068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9abebb0aea2'
down_revision: Union[str, Sequence[str], None] = 'd77dddcce6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['state_code'])
        batch_op.create_unique_constraint(None, ['state_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
