"""test ten

Revision ID: bdcbf9a755f3
Revises: e0ac3835205a
Create Date: 2025-07-07 16:01:27.183866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcbf9a755f3'
down_revision: Union[str, Sequence[str], None] = 'e0ac3835205a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_ten', sa.String(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_nine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('new_column_test_nine', sa.VARCHAR(), nullable=True))
    op.drop_column('restaurants', 'new_column_test_ten')
    # ### end Alembic commands ###
