"""potential changes cant remember'


Revision ID: e04a2d0bb9ef
Revises: 8fac42c92e7c
Create Date: 2025-07-08 19:25:24.844041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04a2d0bb9ef'
down_revision: Union[str, Sequence[str], None] = '8fac42c92e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
