"""added restaurtan address table column city

Revision ID: e0ac3835205a
Revises: cf2d613e0ada
Create Date: 2025-07-07 15:52:53.283715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ac3835205a'
down_revision: Union[str, Sequence[str], None] = 'cf2d613e0ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_addresses', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_addresses', 'city')
    # ### end Alembic commands ###
