"""added menu_item_ingredient_join and ingredient tables

Revision ID: ebcc4f99ce93
Revises: 51a4c00d1105
Create Date: 2025-07-08 13:41:22.745133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcc4f99ce93'
down_revision: Union[str, Sequence[str], None] = '51a4c00d1105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
