"""added phone_number column to admin, field to Response body

Revision ID: f6612a0c6a66
Revises: d9240ad9fae3
Create Date: 2025-07-17 18:53:54.366671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6612a0c6a66'
down_revision: Union[str, Sequence[str], None] = 'd9240ad9fae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'phone_number')
    # ### end Alembic commands ###
