"""updated tables and relationships

Revision ID: ff261b310098
Revises: 5535bcf012d4
Create Date: 2025-07-08 18:58:20.032456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff261b310098'
down_revision: Union[str, Sequence[str], None] = '5535bcf012d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for order_items due to foreign key constraints
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.create_foreign_key('fk_order_items_menu_item_id', 'menu_items', ['menu_item_id'], ['id'])
        batch_op.create_foreign_key('fk_order_items_order_id', 'orders', ['order_id'], ['id'])

    # Add columns to orders (no constraints, so no batch mode needed)
    op.add_column('orders', sa.Column('order_location', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Use batch mode for restaurants due to foreign key constraint
    with op.batch_alter_table('restaurants') as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_admin_id', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for restaurants to drop constraint and column
    with op.batch_alter_table('restaurants') as batch_op:
        batch_op.drop_constraint('fk_restaurants_admin_id', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # Drop columns from orders
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'order_location')

    # Use batch mode for order_items to drop constraints
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.drop_constraint('fk_order_items_order_id', type_='foreignkey')
        batch_op.drop_constraint('fk_order_items_menu_item_id', type_='foreignkey')
    # ### end Alembic commands ###